/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserResponse {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl CreateUserResponse {
    pub fn new(id: i64, username: String, first_name: String, last_name: String, email: String, created_at: String) -> CreateUserResponse {
        CreateUserResponse {
            id,
            username,
            first_name,
            last_name,
            email,
            created_at,
        }
    }
}


