/*
 * Socialapp
 *
 * Socialapp is a generic social network.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ignacio.gomez.arboleda@gmail.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Scope {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
}

impl Scope {
    pub fn new(name: String, description: String) -> Scope {
        Scope {
            id: None,
            name,
            description,
            created_at: None,
        }
    }
}


